### PR TITLE
Update external dependencies

### PR DESCRIPTION
**Pull request by m00head**

### CODE REVIEW

**Comment by m00head** [comment]
Updated external dependencies to latest versions, and built using Android Studio 2.3. Working without crashing when scan is started on device running AOSP 7.1.1 ROM.

Also made changes to resolve the following issues encountered:
```
Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
```

Reflect the following changes in the [material-dialogs](https://github.com/afollestad/material-dialogs) dependency to remove the JitPack Maven repository and fall back to using jCenter instead (the default Maven repository used by Android Studio):
https://github.com/afollestad/material-dialogs/commit/3e69b76ff42008344f9a2787a32ecde535f8904b

Also resolved the following issue I encountered when using the latest Google Support Repository (47.0.0 at the time of writing) with Android Studio 2.3:
http://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3

**Comment by m00head** [comment]
This may also fix #138, #140, and #142

**Comment by m00head** [comment]
@nailyk-fr Please will you review this?

**Comment by nailyk-fr** [comment]
Try to build since I receive your mail but since I change the source from CopperHead to AndroidVTS it fail everytime. Last error: 

> FAILURE: Build failed with an exception.
> * What went wrong:
> A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.afollestad.material-dialogs:core:0.9.4.2.
     Required by:
         project :app


P.S.: Am building '[in-chain](https://github.com/nailyk-fr/jenkins_scripts/blob/nougat-mr1.1-release/AndroidVTS.sh)' and really don't know how gradlew works.

**Comment by m00head** [comment]
I found the issue - the dependency name has changed and no longer has **.github.** in it. Not sure why it built for me - maybe I still had the JitPack Maven version cached or something.

Updated pull request with the fix.

**Comment by nailyk-fr** [comment]
Now it build: 
> [100% 3/3] Install: out/target/product/hammerhead/system/app/AndroidVTS/AndroidVTS.apk
> 
> #### make completed successfully (02:43 (mm:ss)) ####
thanks. I test the [apk](https://releases.nailyk.fr/AndroidVTS/AndroidVTS_2017-03-28.15:30:44_signed.apk) asap.

**Comment by nailyk-fr** [comment]
Build perfect in the Copperhead N toolchain, run perfect on my both z3 ([cm-12.1](https://cloud.githubusercontent.com/assets/16372405/24418253/bc2d9ce6-13eb-11e7-9641-7f2b2043763a.png) & [Lineage-14.1](https://cloud.githubusercontent.com/assets/16372405/24418263/c17330c6-13eb-11e7-9779-7f8115b982be.png)). 
Nice work, thanks! 

P.S.: idk how to make a review on this repo :s

**Comment by m00head** [comment]
To make a review, click on the 'Files changed' tab on the top of this page, then choose the green 'Review changes' button at the top right to get a drop-down box with options to Comment, Approve, or Request changes.

**Comment by nailyk-fr** [comment]
Sorry don't know it was avaiable on the file tab only. 
Not the right place to ask, but why not merge my [Android.mk](https://github.com/nailyk-fr/jenkins_scripts/blob/nougat-mr1.1-release/patches/AndroidVTS.mk)? (mostly extracted from CopperHead one)

**Comment by m00head** [comment]
@Fuzion24 ok to merge this?

**Comment by Fuzion24** [comment]
:+1:

**Pull request merged**
